spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?sslmode=require
    hikari:
      data-source-properties:
        ssl: true
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework   

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    use-root-path: true   